import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Lock, Fingerprint, ArrowLeft, Database, UserPlus, LogIn, ServerCrash, Terminal, Copy, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';

// SQL Schema for the user to copy if needed
const SETUP_SQL = `
-- Enable Storage
insert into storage.buckets (id, name, public) values ('portfolio-images', 'portfolio-images', true);
create policy "Public Access" on storage.objects for select using ( bucket_id = 'portfolio-images' );
create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'portfolio-images' AND auth.role() = 'authenticated' );

-- Create Profile Table
create table public.profile (
  id bigint generated by default as identity primary key,
  name text,
  title text,
  headline text,
  sub_headline text,
  email text,
  avatar_url text,
  socials jsonb
);

-- Create Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  tags text[],
  image_url text,
  live_link text,
  github_link text
);

-- Create Certificates Table
create table public.certificates (
  id bigint generated by default as identity primary key,
  title text,
  issuer text,
  date text,
  image_url text,
  link text
);

-- Create Resume Table
create table public.resume (
  id bigint generated by default as identity primary key,
  type text,
  title text,
  company text,
  period text,
  description text,
  tags text[]
);

-- Create Blogs Table
create table public.blogs (
  id bigint generated by default as identity primary key,
  title text,
  date text,
  link text
);

-- Enable Row Level Security (RLS)
alter table public.profile enable row level security;
alter table public.projects enable row level security;
alter table public.certificates enable row level security;
alter table public.resume enable row level security;
alter table public.blogs enable row level security;

-- Policies (Read Public, Write Authenticated)
create policy "Public Read Profile" on public.profile for select using (true);
create policy "Auth Update Profile" on public.profile for all using (auth.role() = 'authenticated');

create policy "Public Read Projects" on public.projects for select using (true);
create policy "Auth Update Projects" on public.projects for all using (auth.role() = 'authenticated');

create policy "Public Read Certs" on public.certificates for select using (true);
create policy "Auth Update Certs" on public.certificates for all using (auth.role() = 'authenticated');

create policy "Public Read Resume" on public.resume for select using (true);
create policy "Auth Update Resume" on public.resume for all using (auth.role() = 'authenticated');

create policy "Public Read Blogs" on public.blogs for select using (true);
create policy "Auth Update Blogs" on public.blogs for all using (auth.role() = 'authenticated');
`;

export const Login: React.FC = () => {
  const navigate = useNavigate();
  
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [showSql, setShowSql] = useState(false);

  // Check if already logged in
  useEffect(() => {
      if(supabase) {
          (supabase.auth as any).getSession().then(({ data: { session } }: any) => {
              if (session) navigate('/admin');
          });
      }
  }, [navigate]);

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!supabase) {
        setError("Database connection missing. Check lib/supabase.ts");
        return;
    }

    setLoading(true);
    setError('');

    try {
        let result;
        if (mode === 'signup') {
            result = await (supabase.auth as any).signUp({
                email,
                password,
            });
        } else {
            result = await (supabase.auth as any).signInWithPassword({
                email,
                password,
            });
        }

        const { error: authError } = result;

        if (authError) {
            setError(authError.message);
        } else {
            // If signup successful, it might auto-login or require email verification
            // For most Supabase defaults, it auto-logs in unless "Confirm Email" is on.
            if (mode === 'signup') {
                 // Check if session exists immediately
                 const { data: { session } } = await (supabase.auth as any).getSession();
                 if (!session) {
                     setError("Account created! Please check your email to verify before logging in.");
                     setMode('login');
                 } else {
                     navigate('/admin');
                 }
            } else {
                navigate('/admin');
            }
        }
    } catch (err: any) {
        setError(err.message || "Authentication failed");
    } finally {
        setLoading(false);
    }
  };

  const copySql = () => {
      navigator.clipboard.writeText(SETUP_SQL);
      alert("SQL copied to clipboard! Run this in Supabase SQL Editor.");
  };

  return (
    <div className="min-h-screen bg-dark-bg text-dark-text flex items-center justify-center p-4 relative overflow-hidden">
        {/* Background Grid */}
        <div className="absolute inset-0 bg-grid-dark bg-[length:40px_40px] opacity-20 pointer-events-none" />
        
        {/* SQL Modal */}
        <AnimatePresence>
            {showSql && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.9 }}
                        className="bg-[#1a1a1a] border border-white/20 w-full max-w-2xl rounded-lg p-6 shadow-2xl flex flex-col max-h-[80vh]"
                    >
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-xl font-sketch text-white flex items-center gap-2"><Database size={20} /> Initial Database Setup</h3>
                            <button onClick={() => setShowSql(false)}><X className="text-gray-400 hover:text-white" /></button>
                        </div>
                        <div className="bg-black p-4 rounded border border-white/10 overflow-y-auto font-mono text-xs text-green-400 mb-4 flex-1">
                            <pre>{SETUP_SQL}</pre>
                        </div>
                        <button onClick={copySql} className="w-full py-3 bg-dark-accent text-black font-bold font-mono flex items-center justify-center gap-2 hover:bg-white transition-colors">
                            <Copy size={16} /> COPY SQL TO CLIPBOARD
                        </button>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
        
        <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="w-full max-w-md relative z-10 bg-[#0a0a0a] border border-dark-accent/30 p-8 shadow-[0_0_50px_rgba(41,216,255,0.1)]"
            style={{ borderRadius: "2px 20px 2px 20px" }}
        >
            <div className="flex items-center gap-2 mb-8 text-dark-accent/50">
                <button onClick={() => navigate('/')} className="hover:text-dark-accent transition-colors">
                    <ArrowLeft size={20} />
                </button>
                <span className="font-mono text-xs">
                    SECURE_ACCESS_TERMINAL
                </span>
            </div>

            <form onSubmit={handleAuth} className="space-y-6">
                <div className="text-center mb-10">
                    <div className="inline-block p-4 rounded-full bg-dark-accent/10 text-dark-accent mb-4 border border-dark-accent/30">
                        <Lock size={32} />
                    </div>
                    <h1 className="text-3xl font-sketch font-bold text-white">
                        {mode === 'login' ? 'Identity Verification' : 'New Admin Registration'}
                    </h1>
                </div>

                <div className="space-y-2">
                    <label className="text-xs font-mono text-dark-accent uppercase">User ID (Email)</label>
                    <input 
                        type="email" 
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        className="w-full bg-black/50 border-b border-dark-text/20 focus:border-dark-accent py-3 px-4 outline-none transition-colors font-mono text-white placeholder:text-gray-700"
                        placeholder="admin@example.com"
                        required
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs font-mono text-dark-accent uppercase">Passkey</label>
                    <input 
                        type="password" 
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="w-full bg-black/50 border-b border-dark-text/20 focus:border-dark-accent py-3 px-4 outline-none transition-colors font-mono text-white placeholder:text-gray-700"
                        placeholder="••••••••••••"
                        required
                        minLength={6}
                    />
                </div>

                {error && (
                    <div className="p-3 bg-red-900/20 border border-red-500/50 text-red-400 text-sm font-mono flex items-start gap-2">
                        <ServerCrash size={16} className="mt-0.5 shrink-0" />
                        <span>{error}</span>
                    </div>
                )}

                <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    disabled={loading}
                    className="w-full py-4 bg-dark-accent text-black font-bold font-sketch text-lg flex items-center justify-center gap-2 mt-4 hover:bg-white transition-colors"
                >
                    {loading ? (
                        <span className="animate-pulse">PROCESSING...</span>
                    ) : (
                        <>
                            {mode === 'login' ? <Fingerprint size={20} /> : <UserPlus size={20} />}
                            {mode === 'login' ? 'ACCESS DASHBOARD' : 'REGISTER & LOGIN'}
                        </>
                    )}
                </motion.button>
                
                <div className="flex justify-between items-center mt-6 border-t border-white/10 pt-4">
                    <button 
                        type="button"
                        onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}
                        className="text-xs text-gray-500 hover:text-white font-mono flex items-center gap-1"
                    >
                        {mode === 'login' ? (
                            <>NEED ACCOUNT? <span className="text-dark-accent">CREATE ONE</span></>
                        ) : (
                            <>HAVE ACCOUNT? <span className="text-dark-accent">LOGIN</span></>
                        )}
                    </button>

                    <button
                        type="button"
                        onClick={() => setShowSql(true)}
                        className="text-xs text-gray-500 hover:text-dark-accent font-mono flex items-center gap-1"
                    >
                        <Terminal size={12} /> INITIAL SETUP SQL
                    </button>
                </div>
            </form>
        </motion.div>
    </div>
  );
};